apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo-namespace
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: https
      nodePort: 32000
  type: NodePort
