apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: demo-namespace
---
## custom cluster role with create access to tokenreviews
## ref - https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-examples
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-sa-role
rules:
- nonResourceURLs: ["/*"] 
  verbs: ["get", "post"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-sa-role
subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: demo-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-sa-token
  namespace: demo-namespace
  annotations:
    kubernetes.io/service-account.name: demo-sa
type: kubernetes.io/service-account-token