apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: demo-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-sa-token
  namespace: demo-namespace
  annotations:
    kubernetes.io/service-account.name: demo-sa
type: kubernetes.io/service-account-token