apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-proxy-sa
  namespace: demo-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-proxy-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: demo-proxy-sa
    namespace: demo-namespace